import { Colors } from "../theme/colors.slint";
import { StdButton } from "../controls/std_button.slint";
import { CountryFlags, Icons } from "../theme/resources.slint";
import { Metrics } from "../theme/metrics.slint";
import { PlusUsageCard, FreeUsageCard } from "../controls/usage_cards.slint";
import { NewsCard } from "../controls/news_card.slint";

import { AccountStatus, LoginState } from "../ui_state.slint";
import { AnimationBar } from "../controls/animation_bar.slint";

export component HomePage inherits Rectangle {

    background: Colors.background;

    VerticalLayout {

        padding: Metrics.padding_large;
        spacing: Metrics.spacing_medium;

        if AccountStatus.login_status == LoginState.Authenticating : AnimationBar {
            bar_height: Metrics.conn_anime_height;
            bar_color: Colors.std_button;
            running: true;
            background: transparent;
        }

        if AccountStatus.account_level == "Plus" : PlusUsageCard {}
        
        if AccountStatus.account_level == "Free" : FreeUsageCard {}

        NewsCard {
            vertical-stretch: 1;
        }
    }
}