import { StdButton } from "std_button.slint";
import { Typography } from "../theme/typography.slint";
import { Colors } from "../theme/colors.slint";
import { Metrics } from "../theme/metrics.slint";
import { SecretInput } from "secret_input.slint";
import { AnimationBar } from "animation_bar.slint";
import { VerticalLineDivider } from "divider.slint";
import { GridBox } from "std-widgets.slint";
import { AccountStatus } from "../ui_state.slint";

export component LogInCard inherits Rectangle {

    in property <string> helptext_1: "Enter your account secret to log in";
    in property <string> helptext_2: "Or not having an account secret?";

    callback login_clicked(string);
    callback register_clicked();

    VerticalLayout {

        spacing: Metrics.spacing_small;

        Text {
            text: "Log in";
            font-size: Typography.font_section;
            font-weight: Typography.weight_title;
            color: Colors.text_main;
        }

        Rectangle {

            border-radius: Metrics.radius_card;
            border-color: Colors.divider;
            border-width: Metrics.outline_slim;
            background: Colors.card;

            VerticalLayout {
                
                padding: Metrics.padding_large;
                spacing: Metrics.spacing_small;

                secret_input := SecretInput {
                    enter_pressed(secret) => {
                        root.login_clicked(secret);
                    }
                }

                Text {
                    text: helptext_1;
                    font-size: Typography.font_body;
                    color: Colors.text_main;
                }

                login_button := StdButton {
                    btn_text: "Log In";
                    clicked() => {
                        root.login_clicked(secret_input.secret);
                    }
                }

                Text {
                    text: helptext_2;
                    font-size: Typography.font_body;
                    color: Colors.text_main;
                }

                register_button := StdButton {
                    btn_text: "Register";
                    hollowed: true;
                    clicked => {
                        root.register_clicked();
                    }
                }
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }
    }
}

export component AccountInfoCard inherits Rectangle {

    in property <string> secret: AccountStatus.secret;
    in property <string> account_level: AccountStatus.account_level;
    in property <string> plus_expire_date: AccountStatus.expire_date;
    in property <string> invite_code: "ABCDEFGHIJKLMNOP";

    callback manage_account_clicked();
    callback logout_clicked();
    
    VerticalLayout {

        spacing: Metrics.spacing_small;

        Text {
            text: "Account Info";
            font-size: Typography.font_section;
            font-weight: Typography.weight_title;
            color: Colors.text_main;
        }

        Rectangle {

            border-radius: Metrics.radius_card;
            border-color: Colors.divider;
            border-width: Metrics.outline_slim;
            background: Colors.card;

            VerticalLayout {
                
                padding: Metrics.padding_large;
                spacing: Metrics.spacing_medium;

                Text {
                    text: "Account Secret";
                    font-size: Typography.font_body;
                    font-weight: Typography.weight_title;
                    color: Colors.text_main;
                }

                Text {
                    text: secret;
                    font-size: Typography.font_body;
                    color: Colors.text_main;
                }

                VerticalLineDivider {}

                GridLayout {

                    spacing: Metrics.spacing_medium;

                    Row {
                        Text {
                            text: "Account Level";
                            font-size: Typography.font_body;
                            font-weight: Typography.weight_title;
                            color: Colors.text_main;
                        }
                        Text {
                            text: account_level;
                            font-size: Typography.font_body;
                            color: Colors.text_main;
                        }
                    }

                    if account_level == "Plus" :

                    Row {
                        Text {
                            text: "Plus Expire";
                            font-size: Typography.font_body;
                            font-weight: Typography.weight_title;
                            color: Colors.text_main;
                        }
                        Text {
                            text: plus_expire_date;
                            font-size: Typography.font_body;
                            color: Colors.text_main;
                        }
                    }

                    Row {
                        Text {
                            text: "Invite Code";
                            font-size: Typography.font_body;
                            font-weight: Typography.weight_title;
                            color: Colors.text_main;
                        }
                        Text {
                            text: invite_code;
                            font-size: Typography.font_body;
                            color: Colors.text_main;
                        }
                    }
                }

                VerticalLineDivider {}

                Rectangle {
                    vertical-stretch: 1;
                }

                StdButton {
                    btn_text: "Manage Account";
                    clicked => {
                        root.manage_account_clicked();
                    }
                }

                StdButton {
                    btn_text: "Log Out";
                    hollowed: true;
                    clicked => {
                        root.logout_clicked();
                    }
                }

                VerticalLineDivider {}

                StdButton {
                    btn_text: "Delete Account (fast click 10x)";
                    btn_color: Colors.status_dot_red;
                    hollowed: true;
                    clicked => {

                    }
                }
            }
        }
    }
}