import { Colors } from "../theme/colors.slint";

import { ExpandArrow } from "expand_arrow.slint";
import { Typography } from "../theme/typography.slint";
import { CountryFlags, Icons } from "../theme/resources.slint";
import { Metrics } from "../theme/metrics.slint";
import { HorizontalBox } from "std-widgets.slint";

import { ConnInfo, SelectedServer, AccountStatus, LoginState, ConnectionState } from "../ui_state.slint";

export component ConnectionCard inherits Rectangle {

    in property <bool> server_popup_opened: false;

    in property <string> selected_server: 
        SelectedServer.country == "Auto" 
            ? "Automatic" 
            : SelectedServer.country + " / " + SelectedServer.city;

    // matching properties with ConnInfo
    in property <image> conn_indicator:
        ConnInfo.conn_state == ConnectionState.Connected ? Icons.connected_icon :
        ConnInfo.conn_state == ConnectionState.Connecting ? Icons.connecting_icon :
        Icons.disconnected_icon;
    // if Connected, display the exit server from ConnInfo
    // otherwise display the exit server from TunnelSettings.ExitConstraint 
    private property <string> server_name:
        ConnInfo.conn_state == ConnectionState.Connected ? ConnInfo.country + " / " + ConnInfo.city : root.selected_server;
    in property <string> exit_ip: 
        ConnInfo.conn_state == ConnectionState.Connected ? ConnInfo.exit_ip : "Auto-select least loaded server";
    in property <string> flag_country:
        ConnInfo.conn_state == ConnectionState.Connected ? ConnInfo.country : SelectedServer.country;

    callback clicked;

    background: transparent;

    TouchArea {

        mouse-cursor: MouseCursor.pointer;
        clicked => {
            // debug("Selected Server:", SelectedServer.country, SelectedServer.city);
            root.clicked();
        }
    }

    VerticalLayout {

        padding-top: 0px;
        padding-bottom: Metrics.padding-small;
        spacing: Metrics.spacing-tiny;

        // Expand Arrow
        Rectangle {
            height: 16px;

            ExpandArrow {
                expanded: root.server_popup_opened;
            }
        }

        // Country Flag + Server Name + Exit IP
        VerticalLayout {

            alignment: center;

            spacing: Metrics.spacing_tiny;

            selected_server := HorizontalLayout {

                alignment: center;
                spacing: Metrics.spacing_medium;

                if SelectedServer.country != "Auto" : Rectangle {
                    width: self.height / 2 * 3;
                    border-radius: Metrics.radius_flag;
                    clip: true;

                    CountryFlags {
                        country: flag_country;
                        height: server_text.font-size;
                    }
                }

                if SelectedServer.country == "Auto" : Rectangle {
                    width: self.height;
                    border-radius: Metrics.radius_flag;
                    clip: true;

                    CountryFlags {
                        country: flag_country;
                        height: server_text.font-size;
                    }
                }

                server_text := Text {

                    text: root.server_name;
                    color: Colors.text_main;
                    font-size: Typography.font_title;
                    font-weight: Typography.weight_title;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
            }
                
            HorizontalLayout {

                spacing: Metrics.spacing_small;
                alignment: center;

                Image {
                    source: conn_indicator;
                    height: server_text.font-size;
                    width: self.height;
                }

                ip_text := Text {

                    text: root.exit_ip;
                    color: Colors.text_main;
                    font-size: Typography.font_body;
                    vertical-alignment: center;    
                }
            }
        }
    }
}