import { Colors } from "../theme/colors.slint";

export component NavButton inherits Rectangle {

    width: 48px;
    height: 48px;

    in property <bool> selected: false;
    in property <bool> enabled: true;
    in property <image> icon;

    callback clicked();

    background:
        !enabled
            ? #D8D6CE
            : selected
                ? Colors.background
                : Colors.sidebar;

    TouchArea {

        enabled: root.enabled;
        mouse-cursor: MouseCursor.pointer;
        clicked => {
            root.clicked();
        }
    }

    Image {

        source: root.icon;

        width: 28px;
        height: 28px;

        horizontal-alignment: center;
        vertical-alignment: center;
    }
}