import { Metrics } from "../theme/metrics.slint";
import { Colors } from "../theme/colors.slint";
import { Typography } from "../theme/typography.slint";
import { ScrollView } from "std-widgets.slint";

export component NewsCard inherits Rectangle {

    in property <string> news_card_title: "News";

    VerticalLayout {

        spacing: Metrics.spacing_small;

        Text {
            text: news_card_title;
            color: Colors.text_main;
            font-size: Typography.font_section;
            font-weight: Typography.weight_title;
            wrap: word-wrap;
        }

        Rectangle {
            background: Colors.card;
            border-color: Colors.divider;
            border-radius: Metrics.radius_card;
            border-width: Metrics.outline_slim;

            ScrollView {
                // insert news items
                @children
            }
        }
    }    
}