import { Metrics } from "../theme/metrics.slint";
import { Colors } from "../theme/colors.slint";
import { Typography } from "../theme/typography.slint";
import { LineEdit } from "std-widgets.slint";

export component SecretInput inherits Rectangle {

    in property <string> input_propmt: "Enter your account serect here";
    in-out property <string> secret <=> input.text;

    callback enter_pressed(string);

    height: Metrics.pri_button_height;
    border-color: Colors.divider;
    border-width: Metrics.outline_slim;
    border-radius: Metrics.radius_button;
    background: Colors.background;

    VerticalLayout {
        // padding-left: Metrics.padding_medium;

        input := LineEdit {
            placeholder-text: input_propmt;
            input-type: number;
            font-size: Typography.font_section;
            accepted(secret) => {
                enter_pressed(secret);
            }
        }
    }
}