import { Colors } from "../theme/colors.slint";
import { Metrics } from "../theme/metrics.slint";

export component PopupContainer inherits Rectangle {

    in-out property <bool> opened: false;
    in-out property <int> current_page;

    background: transparent;

    clip: true;

    // An overlay to block clicks in UI under the Popup Panel 
    popup_overlay := Rectangle {
        visible: root.opened;

        width: parent.width;
        height: parent.height;

        background: transparent;

        TouchArea {
            width: parent.width;
            height: parent.height;
        }
    }

    // Real Popup Panel
    Rectangle {

       y: opened ? 0px : Metrics.main_window_height - Metrics.title_bar_height - Metrics.bottom_bar_height;

        width: parent.width;
        height: parent.height;

        border-top-left-radius: Metrics.radius_panel;
        border-top-right-radius: Metrics.radius_panel;

        background: Colors.card;

        animate y {
            duration: 150ms;
            easing: ease-out;
        }

        VerticalLayout {
            @children
        }
    }
}