import { ScrollView } from "std-widgets.slint";

import { Colors } from "../theme/colors.slint";
import { Metrics } from "../theme/metrics.slint";
import { CountryFlags } from "../theme/resources.slint";

import { ServerButton, AutoButton, ServerSection, ServerDivider } from "../controls/server_panel.slint";

import { ServerList } from "../ui_state.slint";

export component ServerView inherits Rectangle {
    background: transparent;

    callback server_selected(country: string, city: string);
    callback auto_clicked();

    ScrollView {
        width: parent.width;
        height: parent.height;

        VerticalLayout {

            padding: Metrics.padding_extra;
            spacing: Metrics.spacing_medium;
            
            AutoButton {
                clicked => {
                    root.auto_clicked();
                }
            }

            for section in ServerList.sections : ServerSection {
                    server_type: section.category;
                    // helptext is pending l10n string from rust 
                    // helptext: section.helptext;
                    servers: section.servers;

                    server_button_clicked(country, city) => {
                        root.server_selected(country, city);
                    }
            }    

            // ServerSection {
            //     // mock data for preview
            //     server_type: "Core";
            //     helptext: "Best balance of security and speed for everyday browsing.";

            //     ServerButton {
            //         // mock data for preview
            //         country: "US";
            //         city: "San Jose";
            //         loading: "18%";
            //     }

            //     ServerButton {
            //         // mock data for preview
            //         country: "CA";
            //         city: "Montreal";
            //         loading: "75%";
            //     }

            //     ServerButton {
            //         // mock data for preview
            //         country: "CH";
            //         city: "Zurich";
            //         loading: "8%";
            //     }

            //     ServerButton {
            //         // mock data for preview
            //         country: "CZ";
            //         city: "Prague";
            //         loading: "16%";
            //     }

            //     ServerButton {
            //         // mock data for preview
            //         country: "JP";
            //         city: "Osaka [BETA]";
            //         loading: "10%";
            //     }

            //     ServerButton {
            //         // mock data for preview
            //         country: "SE";
            //         city: "Stockhome [BETA]";
            //         loading: "18%";
            //     }

            //     ServerButton {
            //         // mock data for preview
            //         country: "LT";
            //         city: "Siauliai";
            //         loading: "30%";
            //     }

            //     ServerButton {
            //         // mock data for preview
            //         country: "NL";
            //         city: "Amsterdam";
            //         loading: "81%";
            //     }
            // }

            // ServerDivider {}

            // ServerSection {
            //     // mock data for preview
            //     server_type: "Streaming";
            //     helptext: "Optimized for video services and region-locked media.";

            //     ServerButton {
            //         // mock data for preview
            //         country: "HK";
            //         city: "Jordan";
            //         loading: "11%";
            //     }

            //     ServerButton {
            //         // mock data for preview
            //         country: "TW";
            //         city: "Taipei";
            //         loading: "7%";
            //     }
            // }

            Rectangle {
                vertical-stretch: 1;
            }
        }
    }
}