export global Colors {
    // App Global theme color definition
    out property <color> background: #F2F0E8;
    out property <color> sidebar: #E4DFCE;
    out property <color> accent: #61573A;
    out property <color> title_bar: #dad2be;
    out property <color> bottom_bar: #dad2be;
    out property <color> divider: #afa68b;
    out property <color> hover: #E4DED1;
    out property <color> card: #EEEBE0;
    out property <color> pri_button: #61573A;
    out property <color> std_button: #44aaac;
    out property <color> server_panel: #EEEBE0;

    // Status dot colors
    out property <color> status_dot_red: #d81919;
    out property <color> status_dot_green: #21ca21;
    out property <color> status_dot_yellow: #e5e50e;
    out property <color> status_dot_gray: #888888;

    out property <color> load_high: #ae0505;
    out property <color> load_medium: #bebe0b;
    out property <color> load_low: #5ec405;

    // Font and symbol colors
    out property <color> text_main: #143542;
    out property <color> text_aux: #666666;
    out property <color> symbol: #888888;
}