export global Metrics {

    // UI Component Sizes
    out property <length> main_window_width: 360px;
    out property <length> main_window_height: 640px;
    out property <length> title_bar_height: 48px;
    out property <length> bottom_bar_height: 130px;
    out property <length> side_bar_width: 48px;
    out property <length> conn_anime_height: 8px;
    out property <length> menu_icon_size: 24px;
    out property <length> pri_button_height: 40px;
    out property <length> server_button_height: 32px;

    // Outline
    out property <length> outline_slim: 1px;
    out property <length> outline_thick: 2px;

    // Radius
    out property <length> radius_panel: 24px;
    out property <length> radius_card: 16px;
    out property <length> radius_button: 8px;
    out property <length> radius_anime_bar: 4px;
    out property <length> radius_flag: 2px;

    // Spacing and Paddings
    out property <length> spacing_tiny: 2px;
    out property <length> spacing_small: 4px;
    out property <length> spacing_medium: 8px;
    out property <length> spacing_large: 12px;

    out property <length> padding_small: 4px;
    out property <length> padding_medium: 8px;
    out property <length> padding_large: 12px;
    out property <length> padding_extra: 16px;

    // divider thickness
    out property <length> divider-line: 1px;
}