export global Icons {

    out property <image> gephlogo:
        @image-url("../resources/logos/gephlogo.svg");

    out property <image> gephlogo_gray:
        @image-url("../resources/logos/gephlogo-gray.svg");

    out property <image> gephlogo_yellow_dot:
        @image-url("../resources/logos/gephlogo-yellow-dot.svg");

    out property <image> gephlogo_green_dot:
        @image-url("../resources/logos/gephlogo-green-dot.svg");

    out property <image> gephlogo_red_dot:
        @image-url("../resources/logos/gephlogo-red-dot.svg");

    out property <image> gephlogo_gray_dot:
    @image-url("../resources/logos/gephlogo-gray-dot.svg");

    out property <image> home:
        @image-url("../resources/icons/home.svg");

    out property <image> account:
        @image-url("../resources/icons/user-circle.svg");

    out property <image> settings:
        @image-url("../resources/icons/cog.svg");

    out property <image> about:
        @image-url("../resources/icons/info-circle.svg");

    out property <image> expand_arrow:
        @image-url("../resources/icons/chevron-up.svg");

    out property <image> auto_conn:
        @image-url("../resources/icons/refresh.svg");

    out property <image> disconnected_icon:
        @image-url("../resources/icons/disconnected-circle.svg");

    out property <image> connecting_icon:
        @image-url("../resources/icons/connecting-circle-yellow.svg");

    out property <image> connected_icon:
        @image-url("../resources/icons/connected-circle-green.svg");

    out property <image> buy:
        @image-url("../resources/icons/dollar-circle.svg");

    out property <image> calendar:
        @image-url("../resources/icons/calendar.svg");

    out property <image> data_usage:
        @image-url("../resources/icons/gauge.svg");

    out property <image> plus_icon:
        @image-url("../resources/icons/diamond-alt.svg");

    out property <image> free_icon:
        @image-url("../resources/icons/heart.svg");
}

export component CountryFlags {

    in property <string> country;

    function flag(code: string) -> image {
        if code == "CA" {
            return @image-url("../resources/flags/CA.svg");
        }
        if code == "CH" {
            return @image-url("../resources/flags/CH.svg");
        }
        if code == "CZ" {
            return @image-url("../resources/flags/CZ.svg");
        }
        if code == "JP" {
            return @image-url("../resources/flags/JP.svg");
        }
        if code == "LT" {
            return @image-url("../resources/flags/LT.svg");
        }
        if code == "NL" {
            return @image-url("../resources/flags/NL.svg");
        }
        if code == "PL" {
            return @image-url("../resources/flags/PL.svg");
        }
        if code == "SE" {
            return @image-url("../resources/flags/SE.svg");
        }
        if code == "SG" {
            return @image-url("../resources/flags/SG.svg");
        }
        if code == "US" {
            return @image-url("../resources/flags/US.svg");
        }
        if code == "HK" {
            return @image-url("../resources/flags/HK.svg");
        }
        if code == "TW" {
            return @image-url("../resources/flags/TW.svg");
        }

        return @image-url("../resources/icons/refresh.svg");
    }
    
    Image {
        source: flag(root.country);
        height: parent.height;
    }
}