import { Icons } from "theme/resources.slint";
import {
    LoginState,
    ConnInfo,
    ConnectionState,
    TunnelSettings,
    ServerList,
    ServerSection,
    ServerEntry,
    SelectedServer,
    AccountStatus,
    SettingActions,
} from "ui_state.slint";


export component GephTray inherits SystemTrayIcon {

    icon:
    ConnInfo.conn_state == ConnectionState.Connected
        ? Icons.gephlogo
        : ConnInfo.conn_state == ConnectionState.Connecting
            ? Icons.gephlogo_yellow_dot
            : Icons.gephlogo_gray;

    tooltip: "Geph";

    in property <string> connect_control:
        ConnInfo.conn_state == ConnectionState.Disconnected ? "Connect" :
        ConnInfo.conn_state == ConnectionState.Connecting ? "Cancel" :
        "Disconnect";

    in property <string> selected_server: 
        SelectedServer.country == "Auto" 
            ? "Automatic" 
            : SelectedServer.country + " / " + SelectedServer.city;

    private property <string> server_name:
        ConnInfo.conn_state == ConnectionState.Connected
        ? ConnInfo.country + " / " + ConnInfo.city
        : root.selected_server;

    in property <bool> item_enabled: AccountStatus.login_status != LoggedOut;

    Menu {
        MenuItem {
            title: "Show Geph";
            activated => {
                show_window();
            }
        }

        MenuSeparator {}

        if item_enabled : Menu {
            title: "Server:   " + root.server_name;

            MenuItem {
                title: "Automatic";
                activated => {
                    auto_selected();
                }
            }

            for section in ServerList.sections : Menu {
                title: section.category;
                for server in section.servers : MenuItem {
                    title: server.country + " / " + server.city + " - " + server.load;
                    activated => {
                        exit_selected(server.country, server.city);
                    }
                }
            }    
        }

        if item_enabled : MenuItem {
            title: root.connect_control;
            activated => {
                toggle_connect();
            }
        }

        MenuSeparator {}

        if item_enabled : MenuItem {
            title: "Global VPN";
            checkable: true;
            checked <=> TunnelSettings.global_vpn;
            activated => {
                setting_requested(SettingActions.GlobalVPN);
            }
        }

        if item_enabled : Menu {
            title: "Split Tunneling";
            
            MenuItem {
                title: "Allow LAN Access";
                checkable: true;
                checked <=> TunnelSettings.bypass_lan;
                activated => {
                    setting_requested(SettingActions.BypassLan);
                }
            }
            MenuItem {
                title: "Bypass China";
                checkable: true;
                checked <=> TunnelSettings.bypass_china;
                activated => {
                    setting_requested(SettingActions.BypassChina);
                }
            }       
        }

        MenuSeparator {}

        MenuItem {
            title: "Quit";
            activated => { quit(); }
        }
    }

    callback toggle_connect();
    callback setting_requested(action: SettingActions);

    callback auto_selected();
    callback exit_selected(country: string, city: string);

    callback show_window();
    callback quit();
}