// import { Window, MenuBar, Menu, MenuItem, SystemTrayIcon } from "std-widgets.slint";

export component TestWindow inherits Window {
    width: 400px;
    height: 200px;

    MenuBar {
        Menu {
            title: "Test";

            MenuItem {
                title: "Window Check Test";
                checkable: true;
                checked: true;
            }
        }
    }
}

export component TestTray inherits SystemTrayIcon {
    icon: @image-url("../src/logo-naked-32px.png");
    tooltip: "TEST TOOLTIP";

    Menu {
        MenuItem {
            title: "Tray Check Test";
            checkable: true;
            checked: true;
        }
    }
}